/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Icon:materialSymbols:add': typeof import('~icons/material-symbols/add')['default']
    'Icon:materialSymbols:addNotesOutlineSharp': typeof import('~icons/material-symbols/add-notes-outline-sharp')['default']
    'Icon:materialSymbols:arrowForward': typeof import('~icons/material-symbols/arrow-forward')['default']
    'Icon:materialSymbols:backupTable': typeof import('~icons/material-symbols/backup-table')['default']
    'Icon:materialSymbols:check': typeof import('~icons/material-symbols/check')['default']
    'Icon:materialSymbols:chevronRight': typeof import('~icons/material-symbols/chevron-right')['default']
    'Icon:materialSymbols:close': typeof import('~icons/material-symbols/close')['default']
    'Icon:materialSymbols:conversionPath': typeof import('~icons/material-symbols/conversion-path')['default']
    'Icon:materialSymbols:deleteOutline': typeof import('~icons/material-symbols/delete-outline')['default']
    'Icon:materialSymbols:deleteOutlineRounded': typeof import('~icons/material-symbols/delete-outline-rounded')['default']
    'Icon:materialSymbols:driveFileRenameOutline': typeof import('~icons/material-symbols/drive-file-rename-outline')['default']
    'Icon:materialSymbols:driveFileRenameOutlineOutline': typeof import('~icons/material-symbols/drive-file-rename-outline-outline')['default']
    'Icon:materialSymbols:exclamation': typeof import('~icons/material-symbols/exclamation')['default']
    'Icon:materialSymbols:extensionOutline': typeof import('~icons/material-symbols/extension-outline')['default']
    'Icon:materialSymbols:flashOn': typeof import('~icons/material-symbols/flash-on')['default']
    'Icon:materialSymbols:flipToBack': typeof import('~icons/material-symbols/flip-to-back')['default']
    'Icon:materialSymbols:flipToFront': typeof import('~icons/material-symbols/flip-to-front')['default']
    'Icon:materialSymbols:forwardToInboxOutline': typeof import('~icons/material-symbols/forward-to-inbox-outline')['default']
    'Icon:materialSymbols:homeOutline': typeof import('~icons/material-symbols/home-outline')['default']
    'Icon:materialSymbols:infoOutline': typeof import('~icons/material-symbols/info-outline')['default']
    'Icon:materialSymbols:mailOutline': typeof import('~icons/material-symbols/mail-outline')['default']
    'Icon:materialSymbols:openInNew': typeof import('~icons/material-symbols/open-in-new')['default']
    'Icon:materialSymbols:questionMark': typeof import('~icons/material-symbols/question-mark')['default']
    'Icon:materialSymbols:search': typeof import('~icons/material-symbols/search')['default']
    'Icon:materialSymbols:selectAll': typeof import('~icons/material-symbols/select-all')['default']
    'Icon:materialSymbols:subdirectoryArrowRight': typeof import('~icons/material-symbols/subdirectory-arrow-right')['default']
    'Icon:materialSymbols:unfoldMore': typeof import('~icons/material-symbols/unfold-more')['default']
    'Icon:materialSymbols:warningRounded': typeof import('~icons/material-symbols/warning-rounded')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
