# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend CI

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build-backend:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - run: make publish-backend
      name: Build
    - run: make test-backend
    - name: Publish
      run: make publish-backend
