# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend CI

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build-backend:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'
    - run: make publish-backend
      name: Build
    - run: make test-backend
    - name: Publish Test Report
      if: github.actor != 'dependabot[bot]' && always()
      uses: dorny/test-reporter@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: "backend/**/TestResults.trx"
        name: "Test Report - Contexture Backend"
        reporter: "dotnet-trx"
    - name: Publish
      run: make publish-backend
