# This is a basic workflow to help you get started with Actions

name: CI-Frontend

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - '.github/workflows/CI-frontend.yml'
      - 'frontend-vue/**'

defaults:
  run:
    shell: bash
    working-directory: frontend-vue

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-frontend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run test:unit
      - run: make build-app
        working-directory: ./
