name: Deploy Contexture to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: contexture    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './artifacts/image/'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.X'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - run: make build-backend
      name: Build
    - run: make test-backend
      name: Test
    - name: Setup Elm
      uses: jorelali/setup-elm@v2
    - run: make prepare-image
    - name: prepare scenario
      run: cp ./example/restaurant-db.json ./artifacts/image/db.json
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
