name: Deploy Contexture to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:


# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: contexture    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './artifacts/image/'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.0.X'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'
    - run: make build-backend
      name: Build
    - run: make test-backend
      name: Test
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - run: make prepare-image
    - name: prepare scenario
      run: cp ./example/restaurant-db.json ./artifacts/image/db.json
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
  # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
